In [1]:
import numpy as np
import pandas as pd

In [2]:
#Printar msgs
print("Dale dale dele doli")

#Variaveis dinam tipadas
nome = "Thiago"
idade = 20
peso = 87.5

print(nome, idade, peso)

Dale dale dele doli
Thiago 20 87.5


In [3]:
#Listas (não arrays) podem ter valores diversos
dados = [nome, idade, peso, 13]
print(dados)

#Python ainda tem tuplas ordenadas
ponto = (19, 11, -1)
print(ponto)

#Dicionario tb kappa
dic = {'nome':nome, 'idade':idade, 'peso':peso, 'end':'Rua Herminio Alves de Queiros, 650'}
print(dic['end'])

['Thiago', 20, 87.5, 13]
(19, 11, -1)
Rua Herminio Alves de Queiros, 650


In [4]:
#Condicionais sao feitos da seguinte forma
if idade > 30:
    #Python usa identacao pra definir o nivel/escopo das instrucoes condicionais
    #cuidado pra na fazer caca
    print(nome,"já quase na meia-vida")
    print("Erro!")
else:
    print(nome,"ainda ta jovem")

Thiago ainda ta jovem


In [5]:
#Repeticoes podem ser feitas de duas formas
#Um - usando lacos while
vezes = 1
while vezes <= 5:
    teste = vezes*2
    print("Já passei por aqui {0} vez(es) e vezes x 2 = {1}".format(vezes, teste))
    vezes += 1

Já passei por aqui 1 vez(es) e vezes x 2 = 2
Já passei por aqui 2 vez(es) e vezes x 2 = 4
Já passei por aqui 3 vez(es) e vezes x 2 = 6
Já passei por aqui 4 vez(es) e vezes x 2 = 8
Já passei por aqui 5 vez(es) e vezes x 2 = 10


In [6]:
#Dois - enumerando os elementos de uma lista (objeto interavel)
for vezes in [1, 3, 5, 7, 9]:
    teste = 2*vezes
    print("Ja passei por aqui {0} vez(es) e vezes x 2 = {1}".format(vezes, teste))
print("========================")
#Ou entao
for vezes in range(1,6,1):
    #form in range(inicio, atéExclusivo, incremento)
    print("Já sabem que eu passei por aqui {0} vez(es)".format(vezes))


Ja passei por aqui 1 vez(es) e vezes x 2 = 2
Ja passei por aqui 3 vez(es) e vezes x 2 = 6
Ja passei por aqui 5 vez(es) e vezes x 2 = 10
Ja passei por aqui 7 vez(es) e vezes x 2 = 14
Ja passei por aqui 9 vez(es) e vezes x 2 = 18
Já sabem que eu passei por aqui 1 vez(es)
Já sabem que eu passei por aqui 2 vez(es)
Já sabem que eu passei por aqui 3 vez(es)
Já sabem que eu passei por aqui 4 vez(es)
Já sabem que eu passei por aqui 5 vez(es)


In [7]:
#Python possui um recurso massa pra gerar listas de elementos ja populadas
#Eh tipo assim, cria a variavel com um 'laco' dentro que ja popula
#Nome chique: list comprehension

quadrados = [a**2 for a in range(1,6)]
paresQuadrado = [a**2 for a in range(1,20) if a%2==0]

print(quadrados)
print(paresQuadrado)

#Pode fazer uns bagulho mais doido ainda
primPotencias = [[base**expo for expo in range(4)] for base in range(4)]
print(primPotencias)

[1, 4, 9, 16, 25]
[4, 16, 36, 64, 100, 144, 196, 256, 324]
[[1, 0, 0, 0], [1, 1, 1, 1], [1, 2, 4, 8], [1, 3, 9, 27]]


In [8]:
#É assim que se define funcoes
def quadrado(x):
    return x**2

print(quadrado(3))

#funcoes mais simples podem ser definidas como funcoes lambda lambda lambda nerds
f = lambda x: x**2
print(f(4))

9
16


In [9]:
#Algumas outras coisas legais e uteis
#map = aplica uma funcao a cada elemento de uma lista e retorna o resultado
a = map(f, range(6))
print(a, list(a))

#zip = combina elementos de varios iteraveis em tuplas
a = zip(range(6), map(f, range(6)))
print(a,list(a))

#filter = retorna os elementos de um iteravel para os quais o resultado de uma funcao e verdadeiro
a = filter(lambda x: x%2==0, range(10))
print(a,list(a))

<map object at 0x000001D6EC52BC18> [0, 1, 4, 9, 16, 25]
<zip object at 0x000001D6EC521708> [(0, 0), (1, 1), (2, 4), (3, 9), (4, 16), (5, 25)]
<filter object at 0x000001D6EC52BE48> [0, 2, 4, 6, 8]


In [10]:
#Agora sim a gente vai criar 'arrays' propriamente ditos, ajuda a integrar com C/C++ e Fortran
arr1 = np.array([1,2,3,4,5])
print(type(arr1), arr1)

#Bidimensional
arr2 = np.array([range(5),range(5,10)])
print(arr2)

#Os tamanhos das dimensoes podem ser obtidos com o metdo shape
print(arr1.shape, arr2.shape)

#Pode-se alterar a forma de um vetor mesmo apos a sua criacao
arr2.shape = (2,5)
print(arr2)

<class 'numpy.ndarray'> [1 2 3 4 5]
[[0 1 2 3 4]
 [5 6 7 8 9]]
(5,) (2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [11]:
#NumPy faz operacoes vetorizadas... d o p e
a = np.arange(50,step=5,dtype=np.float)
#form .arrange(kMax, incremento, tipo)
print(a)
arr1 = a.reshape((2,5))
print(arr1)
arr2 = np.linspace(.1,1,num=10,dtype=np.float).reshape((2,5))
print(arr2,"\n=========")
print(arr1 - arr2,"\n=======")
print(arr2*arr1,"\n========")
print(arr1*arr2,"\n========")
print(np.dot(arr2,arr1.T))

[ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45.]
[[ 0.  5. 10. 15. 20.]
 [25. 30. 35. 40. 45.]]
[[0.1 0.2 0.3 0.4 0.5]
 [0.6 0.7 0.8 0.9 1. ]] 
[[-0.1  4.8  9.7 14.6 19.5]
 [24.4 29.3 34.2 39.1 44. ]] 
[[ 0.  1.  3.  6. 10.]
 [15. 21. 28. 36. 45.]] 
[[ 0.  1.  3.  6. 10.]
 [15. 21. 28. 36. 45.]] 
[[ 20.   57.5]
 [ 45.  145. ]]


In [12]:
#Para acessar um elemento, basta informar seu indice em cada eixo
# array(linha, coluna)
print(arr1[1,4])

#Podemos tambem selecionar uma porcao dos elementos (slicing)
aslice = arr1[:, 2:4]
#formato arr1[todas as linhas, colunas 2 e 3]
print(aslice)

#Os resultados de um slice (basico) é uma visao do vetor original
#Ou seja, o vetor pode ser alterado atraves do slice
aslice[:,:] = 0
print(arr1)

45.0
[[10. 15.]
 [35. 40.]]
[[ 0.  5.  0.  0. 20.]
 [25. 30.  0.  0. 45.]]


In [13]:
#NumPy oferece ainda mecanismos para selecao avancada de porcoes
#Mas isso buga aquela ideia do slice, entao se mexer, nao muda o array original
#Usando uma lista de indices
aslice2 = arr1[:,[0, 2, 4]]
print(aslice2)
aslice2[:,:] = 0
print(arr1)

#Ou mascaras booleanas
print(arr1[arr1>10])

[[ 0.  0. 20.]
 [25.  0. 45.]]
[[ 0.  5.  0.  0. 20.]
 [25. 30.  0.  0. 45.]]
[20. 25. 30. 45.]


In [14]:
usuarios = pd.read_csv("http://files.grouplens.org/datasets/movielens/ml-100k/u.user",
                       sep='|',header=None, names=["user_id", "age", "gender", "occupation", "zipcode"])
print(usuarios.shape)
usuarios.head(10)

(943, 5)


user_id  age gender     occupation zipcode
0        1   24      M     technician   85711
1        2   53      F          other   94043
2        3   23      M         writer   32067
3        4   24      M     technician   43537
4        5   33      F          other   15213
5        6   42      M      executive   98101
6        7   57      M  administrator   91344
7        8   36      M  administrator   05201
8        9   29      M        student   01002
9       10   53      M         lawyer   90703

In [15]:
filmes = pd.read_csv(
    "http://files.grouplens.org/datasets/movielens/ml-100k/u.item",
    sep='|',header=None, names=["movie_id", "movie_tittle", "release_date", "video_release_date", "IMDb_URL", "unknown", "Acrion", "Adventure", "Animation", "Children", "Comedy", "Crime", "Documentary", "Drama", "Fantasy", "Film Noir","Horror", "Musical", "Mystery", "Romance", "SciFi", "Thriller", "War", "Western"],
    encoding='latin1')
print(filmes.shape)
filmes.tail(10)

(1682, 24)


movie_id                               movie_tittle release_date  \
1672      1673                              Mirage (1995)  01-Jan-1995   
1673      1674                          Mamma Roma (1962)  01-Jan-1962   
1674      1675                      Sunchaser, The (1996)  25-Oct-1996   
1675      1676                    War at Home, The (1996)  01-Jan-1996   
1676      1677                       Sweet Nothing (1995)  20-Sep-1996   
1677      1678                          Mat' i syn (1997)  06-Feb-1998   
1678      1679                           B. Monkey (1998)  06-Feb-1998   
1679      1680                       Sliding Doors (1998)  01-Jan-1998   
1680      1681                        You So Crazy (1994)  01-Jan-1994   
1681      1682  Scream of Stone (Schrei aus Stein) (1991)  08-Mar-1996   

      video_release_date                                           IMDb_URL  \
1672                 NaN   http://us.imdb.com/M/title-exact?Mirage%20(1995)   
1673                 NaN  http://us.imdb.com/M/title-exact?Mamma%20Roma%...   
1674                 NaN  http://us.imdb.com/M/title-exact?Sunchaser,%20...   
1675                 NaN  http://us.imdb.com/M/title-exact?War%20at%20Ho...   
1676                 NaN  http://us.imdb.com/M/title-exact?Sweet%20Nothi...   
1677                 NaN  http://us.imdb.com/M/title-exact?Mat%27+i+syn+...   
1678                 NaN  http://us.imdb.com/M/title-exact?B%2E+Monkey+(...   
1679                 NaN      http://us.imdb.com/Title?Sliding+Doors+(1998)   
1680                 NaN  http://us.imdb.com/M/title-exact?You%20So%20Cr...   
1681                 NaN  http://us.imdb.com/M/title-exact?Schrei%20aus%...   

      unknown  Acrion  Adventure  Animation  Children   ...     Fantasy  \
1672        0       1          0          0         0   ...           0   
1673        0       0          0          0         0   ...           0   
1674        0       0          0          0         0   ...           0   
1675        0       0          0          0         0   ...           0   
1676        0       0          0          0         0   ...           0   
1677        0       0          0          0         0   ...           0   
1678        0       0          0          0         0   ...           0   
1679        0       0          0          0         0   ...           0   
1680        0       0          0          0         0   ...           0   
1681        0       0          0          0         0   ...           0   

      Film Noir  Horror  Musical  Mystery  Romance  SciFi  Thriller  War  \
1672          0       0        0        0        0      0         1    0   
1673          0       0        0        0        0      0         0    0   
1674          0       0        0        0        0      0         0    0   
1675          0       0        0        0        0      0         0    0   
1676          0       0        0        0        0      0         0    0   
1677          0       0        0        0        0      0         0    0   
1678          0       0        0        0        1      0         1    0   
1679          0       0        0        0        1      0         0    0   
1680          0       0        0        0        0      0         0    0   
1681          0       0        0        0        0      0         0    0   

      Western  
1672        0  
1673        0  
1674        0  
1675        0  
1676        0  
1677        0  
1678        0  
1679        0  
1680        0  
1681        0  

[10 rows x 24 columns]

In [16]:
avaliacoes = pd.read_csv(
"http://files.grouplens.org/datasets/movielens/ml-100k/u.data",
sep='\t',header=None, names=["user_id", "movie_id", "rating","timestamp"])
print(avaliacoes.shape)
avaliacoes.head()

(100000, 4)


user_id  movie_id  rating  timestamp
0      196       242       3  881250949
1      186       302       3  891717742
2       22       377       1  878887116
3      244        51       2  880606923
4      166       346       1  886397596

In [17]:
print(usuarios.describe(), "\n")
print(usuarios.dtypes)

          user_id         age
count  943.000000  943.000000
mean   472.000000   34.051962
std    272.364951   12.192740
min      1.000000    7.000000
25%    236.500000   25.000000
50%    472.000000   31.000000
75%    707.500000   43.000000
max    943.000000   73.000000 

user_id        int64
age            int64
gender        object
occupation    object
zipcode       object
dtype: object


In [18]:
print(filmes.dtypes)

movie_id                int64
movie_tittle           object
release_date           object
video_release_date    float64
IMDb_URL               object
unknown                 int64
Acrion                  int64
Adventure               int64
Animation               int64
Children                int64
Comedy                  int64
Crime                   int64
Documentary             int64
Drama                   int64
Fantasy                 int64
Film Noir               int64
Horror                  int64
Musical                 int64
Mystery                 int64
Romance                 int64
SciFi                   int64
Thriller                int64
War                     int64
Western                 int64
dtype: object
